files:
  include: '**/*.scss'
rules:
  hex-length:
    - 1
    - style: long
  no-vendor-prefixes: 0
  single-line-per-selector: 0
  property-sort-order:
    - 1
    - order: smacss
  no-mergeable-selectors: 0
  empty-line-between-blocks: 0
  force-pseudo-nesting: 0
  force-element-nesting: 0
  no-url-domains: 0
  no-url-protocols: 0
  no-duplicate-properties: 0
  leading-zero: 0
  no-trailing-zero: 0
  no-qualifying-elements: 0
  nesting-depth: 0
  indentation: 0
  no-ids: 0,
  class-name-format: 0
  mixins-before-declarations: 0
  no-important: 0
